services:
  - type: web
    name: dicte-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dictation_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        value: postgres://dicte_user:1dt2tsTB8fZv1xNLQG12PYD9ZmidM8Xr@dpg-d0un2mc9c44c73bf6ac0-a.oregon-postgres.render.com:5432/dicte
      - key: REDIS_URL
        fromService:
          type: redis
          name: dicte-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://dicte-frontend.vercel.app
      - key: DEBUG
        value: false

databases:
  - name: dicte-db
    databaseName: dicte
    user: dicte_user
    plan: free

services:
  - type: redis
    name: dicte-redis
    plan: free 