# Generated by Django 5.1.6 on 2025-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
