# Generated by Django 5.1.6 on 2025-06-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_dictation_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationattempt',
            name='corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
